In [5]:
import numpy as np

In [7]:
A=np.array([[3,-2,-1],[-4,7,-1],[2,-3,1]])
B=np.array([12,0,0])
B=np.transpose(B)
print(A)
print(B)

[[ 3 -2 -1]
 [-4  7 -1]
 [ 2 -3  1]]
[12  0  0]


In [10]:
Ai=np.linalg.inv(A)
print(Ai)

[[ 0.4  0.5  0.9]
 [ 0.2  0.5  0.7]
 [-0.2  0.5  1.3]]


In [12]:
X=Ai*B
print(X)

[[ 4.8  0.   0. ]
 [ 2.4  0.   0. ]
 [-2.4  0.   0. ]]
