In [1]:
import numpy as np


In [3]:
x=np.array([[4,89,1],[9,124,1],[5,103,1]])
print(x)

[[  4  89   1]
 [  9 124   1]
 [  5 103   1]]


In [4]:
y=np.array([16,28,20])
y=np.transpose(y)
print(y)

[16 28 20]


In [23]:
a=np.linalg.inv(np.dot(np.transpose(x),x))
b=np.dot(a,np.transpose(x))
theta=np.dot(b,y)

In [24]:
print(theta)

[ 0.8         0.22857143 -7.54285714]
